- esa_archiver.gemspec
リポジトリを公開するためには概要とホームページを載せる必要がある。
そのためgemspecに内容を書いた。
まだないのでテストしていない
> gemspecにリポジトリの内容を書いた

- README.md
このリポジトリを公開できるようにREADMEを書く。
なし。
> READMEにリポジトリの説明を書いた

- README.md
コードを月数指定から日数指定に変更したので、READMEを更新する。
> READMEを日付指定のものに修正した

- lib/esa_archiver/gateways/esa_client.rb
- spec/gateways/esa_client_spec.rb
記事の作成日を見てアーカイブしたいという要望があったので修正する。
esaクエリを`updated:xxx`から`created:xxx`に修正する。
テストが通ることを確認した。
> 記事の作成日を見るようにした

- docker-compose.yml
テストの度にbundle installをするのが面倒なのでdocker-composeファイルを作成する。
`docker-compose up`でアーカイブが実行されるようにする。
`docker-compose up`でアーカイブが実行されることを確認した。
> docker-compose.ymlを追加した

- .env.sample
.env.sampleのどの変数にどんなものを設定したら良いか、わかりにくいので追記する。
> .env.sampleに環境変数の説明を追加した

- lib/esa_archiver/gateways/esa_client.rb
既にメンバーがチームから退会している場合に、記事のアーカイブ者として記事の作成者を指定できないためエラーが発生する。これを解決する。
記事の作成者をアーカイブ者として指定できなかった場合に、アーカイブ者を`esa_bot`としてリトライする。
レスポンスボディにエラーが含まれている場合に、`esa_bot`としてアーカイブの再試行を行う。
esaチームから退会済のユーザの記事をアーカイブする際に、esa_botとしてアーカイブの再試行を行うことを確認した。
> 記事のアーカイブ時にエラーが発生した場合にesa_botとしてアーカイブを再試行する

- .rubocop.yml
- esa_archiver.gemspec
- lib/esa_archiver/gateways/esa_client.rb
- spec/use_cases/archive_spec.rb
#28 でCircleCI 2.0に移行した際に、Rubocopで警告がでていたので解消する。
- Rubocopの警告に従って修正する
テストが通ることを確認した。
> Rubocopが落ちていたので修正した

- .circleci/config.yml
- Dockerfile
- Gemfile
- Gemfile.lock
Rubyのバージョンが古いのでアップデートする。
- 最新版の2.5.3にアップデートする
テストが通ることを確認した。
> Ruby2.5.0からRuby2.5.3にアップデートした

- .circleci/config.yml
- Dockerfile
- Gemfile
- Gemfile.lock
動作確認を行うRubyバージョンを2.6.0にアップデートする。
- Ruby:2.5.3 -> Ruby:2.6.0
テストが通ることを確認した。
> update to Ruby:2.6

- .circleci/config.yml
- Gemfile
複数のRubyバージョンでテストを行う。
- Ruby:2.4以降の最新メジャーバージョンを1つずつテストする
Ruby:2.4.5, Ruby: 2.5.3, Ruby:2.6.0の3バージョンでテストが通ることを確認した。
> 複数のRubyバージョンでテストするようにした

- .circleci/config.yml
- Dockerfile
- Gemfile.lock
Ruby:2.6.1に更新する。
- DockerfileのRubyバージョンを`2.6.1`に更新する
- CircleCIでRuby2.6台のテストを`2.6.1`に更新する
テストが通ることを確認した。
> update to ruby:2.6.1

- .circleci/config.yml
- Dockerfile
テストするRubyバージョンを最新のものに更新した。
以下のバージョンでテストするように修正する
- Ruby:2.4.6
- Ruby:2.5.5
- Ruby:2.6.3
テストが通ることを確認した。
> Rubyのバージョンを最新のものに更新した

- .circleci/config.yml
CircleCI workflowを用いた複数バージョンテストにする。
- CircleCI workflowを導入する
CIが通ることを確認した。
> test on CircleCI workflow

- .circleci/config.yml
- README.md
Reverts Pegasus204/esa_archiver#81
I am upgraded to Performance Plan of CircleCI.
> Revert "Change CI from CircleCI to GitHub"

- .circleci/config.yml
- Dockerfile
> Rubyのバージョンを更新した

- .dependabot/config.yml
- .github/dependabot.yml
((事前に書いてある文書は説明用のものです。 レビュー前には消してください))
* このPRをマージすると以下のことができるようになるよ!
* 仕様書や関連プルリクエストへのリンク
* (UIの変更がある場合)こういうUIになるよ/こういう動作になるよ！
* スクリーンショットや動画キャプチャ
* 何を考えてこのプルリクを作ったか。
* 考えた結果、除外したものがあれば書いてほしい
* 方針に沿って実装していく中でレビュアーに伝えたいこと
* 適宜、図や疑似コードを使う
* コードへのコメントでもよい
* マージボタンを押してもらうための材料
* 確認した項目など
* JS/view/CSS周りの変更なら確認したブラウザも記載
* 書いてみたけど自信がないところとか
> setup dependabot v2

- .github/dependabot.yml
((事前に書いてある文書は説明用のものです。 レビュー前には消してください))
* このPRをマージすると以下のことができるようになるよ!
* 仕様書や関連プルリクエストへのリンク
* (UIの変更がある場合)こういうUIになるよ/こういう動作になるよ！
* スクリーンショットや動画キャプチャ
* 何を考えてこのプルリクを作ったか。
* 考えた結果、除外したものがあれば書いてほしい
* 方針に沿って実装していく中でレビュアーに伝えたいこと
* 適宜、図や疑似コードを使う
* コードへのコメントでもよい
* マージボタンを押してもらうための材料
* 確認した項目など
* JS/view/CSS周りの変更なら確認したブラウザも記載
* 書いてみたけど自信がないところとか
> Reviewerを追加した

- .github/dependabot.yml
((事前に書いてある文書は説明用のものです。 レビュー前には消してください))
* このPRをマージすると以下のことができるようになるよ!
* 仕様書や関連プルリクエストへのリンク
* (UIの変更がある場合)こういうUIになるよ/こういう動作になるよ！
* スクリーンショットや動画キャプチャ
* 何を考えてこのプルリクを作ったか。
* 考えた結果、除外したものがあれば書いてほしい
* 方針に沿って実装していく中でレビュアーに伝えたいこと
* 適宜、図や疑似コードを使う
* コードへのコメントでもよい
* マージボタンを押してもらうための材料
* 確認した項目など
* JS/view/CSS周りの変更なら確認したブラウザも記載
* 書いてみたけど自信がないところとか
> add docker to dependabot dependency monitoring

- .github/workflows/test.yml
- CIのRubyバージョンに3.0を追加した
- それぞれの最新版が使えるようにパッチバージョンをxにした
((事前に書いてある文書は説明用のものです。 レビュー前には消してください))
* このPRをマージすると以下のことができるようになるよ!
* 仕様書や関連プルリクエストへのリンク
* (UIの変更がある場合)こういうUIになるよ/こういう動作になるよ！
* スクリーンショットや動画キャプチャ
* 何を考えてこのプルリクを作ったか。
* 考えた結果、除外したものがあれば書いてほしい
* 方針に沿って実装していく中でレビュアーに伝えたいこと
* 適宜、図や疑似コードを使う
* コードへのコメントでもよい
* マージボタンを押してもらうための材料
* 確認した項目など
* JS/view/CSS周りの変更なら確認したブラウザも記載
* 書いてみたけど自信がないところとか
> CIのRubyバージョンに3.0を追加した
